### ISSUE TITLE
TODO before merge to core

### ISSUE THREAD

**Issue by bdraco** [briis/unifiprotect#347]
- [x] select & other cleanups https://github.com/briis/unifiprotect/pull/346
- [ ] raise `ConfigEntryAuthFailed`
- [ ] Remove support for non-unifios from config flow (don't ask port)
- [ ] Reauth flow (https://developers.home-assistant.io/docs/config_entries_config_flow_handler/#reauthentication)
- [ ] Drop custom services that overlap with the select entities

**Comment by AngellusMortis** [comment]
I think we should keep the ask for port. It should be 443 for _most_ people, but if someone has a reverse proxy in front of their UFP instance, the port could be something else.

Can you clarify what you were thinking for reauth flow?

**Comment by bdraco** [comment]
https://developers.home-assistant.io/docs/config_entries_config_flow_handler/#reauthentication

**Comment by bdraco** [comment]
> I think we should keep the ask for port. It should be 443 for _most_ people, but if someone has a reverse proxy in front of their UFP instance, the port could be something else.

We should adjust the doc string to remove `Non` unifios

**Comment by AngellusMortis** [comment]
I am going to merge this checklist into https://github.com/briis/unifiprotect/issues/19
